name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  checks:
    runs-on: [self-hosted, nixos, hetzner]
    steps:
      - uses: actions/checkout@v4

      - name: Run CI
        run: nix run .#ci
